/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';

export function getArchiveChangeSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-archive-change',
    description: 'Arquiva uma change concluída no workflow experimental. Use quando o usuário quiser finalizar e arquivar uma change após a implementação estar completa.',
    instructions: `Arquiva uma change concluída no workflow experimental.

**Entrada**: Opcionalmente especifique um nome de change. Se omitido, verifique se pode ser inferido do contexto da conversa. Se vago ou ambíguo, você DEVE solicitar as changes disponíveis.

**Passos**

1. **Se nenhum nome de change for fornecido, solicite a seleção**

   Execute \`openspec list --json\` para obter as changes disponíveis. Use a ferramenta **AskUserQuestion** para permitir que o usuário selecione.

   Mostre apenas as changes ativas (não arquivadas).
   Inclua o schema usado para cada change, se disponível.

   **IMPORTANTE**: NÃO adivinhe ou selecione automaticamente uma change. Sempre deixe o usuário escolher.

2. **Verifique o status de conclusão dos artifacts**

   Execute \`openspec status --change "<nome>" --json\` para verificar a conclusão dos artifacts.

   Analise o JSON para entender:
   - \`schemaName\`: O workflow sendo usado
   - \`artifacts\`: Lista de artifacts com seu status (\`done\`, \`skipped\` ou outro)

   **Se algum artifact não estiver \`done\` nem \`skipped\`** (artifacts ignorados satisfazem o requisito - a change declara skip_specs):
   - Exiba um aviso listando os artifacts incompletos
   - Use a ferramenta **AskUserQuestion** para confirmar se o usuário deseja prosseguir
   - Prossiga se o usuário confirmar

3. **Verifique o status de conclusão das tarefas**

   Execute \`openspec status --change "<nome>" --json\` e use \`artifactPaths\` para localizar o artifact de tarefas do schema ativo (tipicamente \`tasks\`, mas confira o JSON).

   Leia os caminhos em \`artifactPaths.<id>.existingOutputPaths\` (ou o equivalente retornado) em vez de assumir \`tasks.md\`.

   Use o formato de conclusão definido pelo schema ativo e pela saída de \`openspec instructions apply --change "<nome>" --json\` (lista de tarefas e instrução dinâmica) para contar pendentes vs concluídas.

   **Se tarefas incompletas forem encontradas:**
   - Exiba um aviso mostrando a quantidade de tarefas incompletas
   - Use a ferramenta **AskUserQuestion** para confirmar se o usuário deseja prosseguir
   - Prossiga se o usuário confirmar

   **Se não existir artifact de tarefas:** Prossiga sem aviso relacionado a tarefas.

4. **Avalie o estado de sincronização dos delta specs**

   Execute \`openspec status --change "<nome>" --json\` e leia \`artifactPaths\` para localizar delta specs (tipicamente sob o artifact \`specs\`). Use apenas os caminhos retornados — não assuma \`openspec/changes/<nome>/specs/\`.

   Se nenhum delta spec existir nos caminhos retornados, prossiga sem prompt de sync.

   **Se delta specs existirem:**
   - Compare cada delta spec com seu spec principal correspondente em \`openspec/specs/\`
   - Determine quais alterações seriam aplicadas (adições, modificações, remoções, renomeações)
   - Mostre um resumo combinado antes de solicitar

   **Opções de prompt:**
   - Se alterações forem necessárias: "Sincronizar agora (recomendado)", "Arquivar sem sincronizar"
   - Se já estiver sincronizado: "Arquivar agora", "Sincronizar mesmo assim", "Cancelar"

   Encaminhe conforme a resposta:
   - "Cancelar" — pare, não arquive
   - "Arquivar sem sincronizar" ou "Arquivar agora" — prossiga para o arquivamento
   - "Sincronizar agora" ou "Sincronizar mesmo assim" — sincronize, depois verifique (abaixo)
   - Qualquer outra resposta — pergunte novamente em vez de arquivar

   Para sincronizar, execute o workflow \`openspec-sync-specs\` inline (merge inteligente dirigido por agente) para a change '<nome>', passando a análise de delta spec acima, e aguarde a conclusão. Não o delegue a uma tarefa em background — o passo 5 moveria o diretório da change enquanto um sync ainda o lê, deixando a change arquivada e os specs principais nunca atualizados. Se o seu agente só conseguir executá-lo por delegação, delegue de forma síncrona e aguarde o resultado.

   Em seguida, refaça a comparação do topo deste passo contra cada capability que tem um delta spec em \`artifactPaths.specs.existingOutputPaths\` — não apenas as que o sync reporta ter tocado. Um sync bem-sucedido não deixa nada para aplicar, então cada capability deve agora constar como já sincronizada:
   - Requisitos ADDED presentes
   - Requisitos MODIFIED carregando as alterações de cenário e descrição nomeadas no delta, com seus demais cenários intactos
   - Requisitos REMOVED ausentes
   - Requisitos RENAMED presentes sob o novo nome e ausentes sob o antigo

   Se o sync falhar, ou qualquer capability não corresponder, reporte a divergência e pare — não arquive. Nada foi movido e o diretório da change está intacto, então o usuário pode corrigir a inconsistência ou reexecutar o sync e iniciar o arquivamento novamente.

5. **Realize o arquivamento**

   Use o CLI para mover a change de forma atômica:

   \`\`\`bash
   openspec archive "<nome>"
   \`\`\`

   O comando trata colisões no destino, prefixo de data e validação. O nome de destino (\`<target-name>\`) usa o nome da change como está quando ele já começa com um prefixo \`YYYY-MM-DD-\`; caso contrário, a data atual é prefixada como \`YYYY-MM-DD-<nome>\` — nunca empilhe uma segunda data (mesma regra do \`openspec archive\`). Se o destino já existir, falhe com erro e sugira renomear o arquivo existente ou usar outra data — **não** use \`mv\` manual nem aninhe o diretório da change.

6. **Exiba o resumo**

   Mostre o resumo de conclusão do arquivamento incluindo:
   - Nome da change
   - Schema que foi usado
   - Local do arquivo
   - Se os specs foram sincronizados (se aplicável)
   - Observação sobre quaisquer avisos (artifacts/tarefas incompletos)

**Saída em Sucesso**

\`\`\`markdown
## Arquivamento Concluído

**Change:** <nome-change>
**Schema:** <nome-schema>
**Arquivado em:** openspec/changes/archive/<target-name>/
**Specs:** <"✓ Sincronizados com os specs principais" somente se a verificação do passo 4 passou; caso contrário "Sem delta specs" ou "Sincronização ignorada">

<"Todos os artifacts completos. Todas as tarefas completas." — ou, se arquivado com avisos, liste-os em vez disso (ex.: "Arquivado com 2 tarefas incompletas")>
\`\`\`

**Guardrails**
- Sempre solicite a seleção da change se não fornecida
- Use o grafo de artifacts (openspec status --json) para verificação de conclusão
- Não bloqueie o arquivamento por avisos - apenas informe e confirme
- Preservar .openspec.yaml ao mover para o arquivo (ele move com o diretório)
- Mostre um resumo claro do que aconteceu
- Se sync for solicitado, execute o workflow \`openspec-sync-specs\` inline (agent-driven)
- Nunca arquive enquanto um sync de specs ainda estiver em andamento — execute o sync inline e verifique os specs principais antes de mover o diretório da change
- Se delta specs existirem, sempre execute a avaliação de sync e mostre o resumo combinado antes de solicitar`,
    license: 'MIT',
    compatibility: 'Requer openspec CLI.',
    metadata: { author: 'openspec', version: '1.0' },
  };
}

export function getOpsxArchiveCommandTemplate(): CommandTemplate {
  return {
    name: 'OPSX: Archive',
    description: 'Arquiva uma change concluída no workflow experimental',
    category: 'Workflow',
    tags: ['workflow', 'archive', 'experimental'],
    content: `Arquiva uma change concluída no workflow experimental.

**Entrada**: Opcionalmente especifique um nome de change após \`/opsx:archive\` (por exemplo, \`/opsx:archive add-auth\`). Se omitido, verifique se pode ser inferido do contexto da conversa. Se vago ou ambíguo, você DEVE solicitar as changes disponíveis.

**Passos**

1. **Se nenhum nome de change for fornecido, solicite a seleção**

   Execute \`openspec list --json\` para obter as changes disponíveis. Use a ferramenta **AskUserQuestion** para permitir que o usuário selecione.

   Mostre apenas as changes ativas (não arquivadas).
   Inclua o schema usado para cada change, se disponível.

   **IMPORTANTE**: NÃO adivinhe ou selecione automaticamente uma change. Sempre deixe o usuário escolher.

2. **Verifique o status de conclusão dos artifacts**

   Execute \`openspec status --change "<nome>" --json\` para verificar a conclusão dos artifacts.

   Analise o JSON para entender:
   - \`schemaName\`: O workflow sendo usado
   - \`artifacts\`: Lista de artifacts com seu status (\`done\`, \`skipped\` ou outro)

   **Se algum artifact não estiver \`done\` nem \`skipped\`** (artifacts ignorados satisfazem o requisito - a change declara skip_specs):
   - Exiba um aviso listando os artifacts incompletos
   - Solicite confirmação do usuário para continuar
   - Prossiga se o usuário confirmar

3. **Verifique o status de conclusão das tarefas**

   Execute \`openspec status --change "<nome>" --json\` e use \`artifactPaths\` para localizar o artifact de tarefas do schema ativo (tipicamente \`tasks\`, mas confira o JSON).

   Leia os caminhos em \`artifactPaths.<id>.existingOutputPaths\` (ou o equivalente retornado) em vez de assumir \`tasks.md\`.

   Use o formato de conclusão definido pelo schema ativo e pela saída de \`openspec instructions apply --change "<nome>" --json\` para contar pendentes vs concluídas.

   **Se tarefas incompletas forem encontradas:**
   - Exiba um aviso mostrando a quantidade de tarefas incompletas
   - Solicite confirmação do usuário para continuar
   - Prossiga se o usuário confirmar

   **Se não existir artifact de tarefas:** Prossiga sem aviso relacionado a tarefas.

4. **Avalie o estado de sincronização dos delta specs**

   Execute \`openspec status --change "<nome>" --json\` e leia \`artifactPaths\` para localizar delta specs (tipicamente sob o artifact \`specs\`). Use apenas os caminhos retornados — não assuma \`openspec/changes/<nome>/specs/\`.

   Se nenhum delta spec existir nos caminhos retornados, prossiga sem prompt de sync.

   **Se delta specs existirem:**
   - Compare cada delta spec com seu spec principal correspondente em \`openspec/specs/\`
   - Determine quais alterações seriam aplicadas (adições, modificações, remoções, renomeações)
   - Mostre um resumo combinado antes de solicitar

   **Opções de prompt:**
   - Se alterações forem necessárias: "Sincronizar agora (recomendado)", "Arquivar sem sincronizar"
   - Se já estiver sincronizado: "Arquivar agora", "Sincronizar mesmo assim", "Cancelar"

   Encaminhe conforme a resposta:
   - "Cancelar" — pare, não arquive
   - "Arquivar sem sincronizar" ou "Arquivar agora" — prossiga para o arquivamento
   - "Sincronizar agora" ou "Sincronizar mesmo assim" — sincronize, depois verifique (abaixo)
   - Qualquer outra resposta — pergunte novamente em vez de arquivar

   Para sincronizar, execute o workflow \`openspec-sync-specs\` inline (merge inteligente dirigido por agente) para a change '<nome>', passando a análise de delta spec acima, e aguarde a conclusão. Não o delegue a uma tarefa em background — o passo 5 moveria o diretório da change enquanto um sync ainda o lê, deixando a change arquivada e os specs principais nunca atualizados. Se o seu agente só conseguir executá-lo por delegação, delegue de forma síncrona e aguarde o resultado.

   Em seguida, refaça a comparação do topo deste passo contra cada capability que tem um delta spec em \`artifactPaths.specs.existingOutputPaths\` — não apenas as que o sync reporta ter tocado. Um sync bem-sucedido não deixa nada para aplicar, então cada capability deve agora constar como já sincronizada:
   - Requisitos ADDED presentes
   - Requisitos MODIFIED carregando as alterações de cenário e descrição nomeadas no delta, com seus demais cenários intactos
   - Requisitos REMOVED ausentes
   - Requisitos RENAMED presentes sob o novo nome e ausentes sob o antigo

   Se o sync falhar, ou qualquer capability não corresponder, reporte a divergência e pare — não arquive. Nada foi movido e o diretório da change está intacto, então o usuário pode corrigir a inconsistência ou reexecutar o sync e iniciar o arquivamento novamente.

5. **Realize o arquivamento**

   Use o CLI para mover a change de forma atômica:

   \`\`\`bash
   openspec archive "<nome>"
   \`\`\`

   O comando trata colisões no destino, prefixo de data e validação. O nome de destino (\`<target-name>\`) usa o nome da change como está quando ele já começa com um prefixo \`YYYY-MM-DD-\`; caso contrário, a data atual é prefixada como \`YYYY-MM-DD-<nome>\` — nunca empilhe uma segunda data (mesma regra do \`openspec archive\`). Se o destino já existir, falhe com erro e sugira renomear o arquivo existente ou usar outra data — **não** use \`mv\` manual nem aninhe o diretório da change.

6. **Exiba o resumo**

   Mostre o resumo de conclusão do arquivamento incluindo:
   - Nome da change
   - Schema que foi usado
   - Local do arquivo
   - Status de sincronização dos specs (sincronizado / sincronização ignorada / sem delta specs)
   - Observação sobre quaisquer avisos (artifacts/tarefas incompletos)

**Saída em Sucesso**

\`\`\`markdown
## Arquivamento Concluído

**Change:** <nome-change>
**Schema:** <nome-schema>
**Arquivado em:** openspec/changes/archive/<target-name>/
**Specs:** ✓ Sincronizados com os specs principais

<"Todos os artifacts completos. Todas as tarefas completas." — ou, se arquivado com avisos, liste-os em vez disso (ex.: "Arquivado com 2 tarefas incompletas")>
\`\`\`

**Saída em Sucesso (Sem Delta Specs)**

\`\`\`markdown
## Arquivamento Concluído

**Change:** <nome-change>
**Schema:** <nome-schema>
**Arquivado em:** openspec/changes/archive/<target-name>/
**Specs:** Sem delta specs

Todos os artifacts completos. Todas as tarefas completas.
\`\`\`

**Saída em Sucesso com Avisos**

\`\`\`markdown
## Arquivamento Concluído (com avisos)

**Change:** <nome-change>
**Schema:** <nome-schema>
**Arquivado em:** openspec/changes/archive/<target-name>/
**Specs:** Sincronização ignorada (usuário escolheu ignorar)

**Avisos:**
- Arquivado com 2 artifacts incompletos
- Arquivado com 3 tarefas incompletas
- Sincronização de delta spec foi ignorada (usuário escolheu ignorar)

Revise o arquivo se isso não foi intencional.
\`\`\`

**Saída em Erro (Arquivo Existe)**

\`\`\`markdown
## Arquivamento Falhou

**Change:** <nome-change>
**Destino:** openspec/changes/archive/<target-name>/

O diretório de arquivo de destino já existe.

**Opções:**
1. Renomear o arquivo existente
2. Excluir o arquivo existente se for uma duplicata
3. Aguardar até uma data diferente para arquivar
\`\`\`

**Guardrails**
- Sempre solicite a seleção da change se não fornecida
- Use o grafo de artifacts (openspec status --json) para verificação de conclusão
- Não bloqueie o arquivamento por avisos - apenas informe e confirme
- Preservar .openspec.yaml ao mover para o arquivo (ele move com o diretório)
- Mostre um resumo claro do que aconteceu
- Se sync for solicitado, execute o workflow \`openspec-sync-specs\` inline (agent-driven)
- Nunca arquive enquanto um sync de specs ainda estiver em andamento — execute o sync inline e verifique os specs principais antes de mover o diretório da change
- Se delta specs existirem, sempre execute a avaliação de sync e mostre o resumo combinado antes de solicitar`
  };
}
