/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';
import { CODE_REVIEW_TEMPLATE_MESSAGES } from '../../../messages/index.js';

export function getCodeReviewSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-code-review',
    description: CODE_REVIEW_TEMPLATE_MESSAGES.skillDescription,
    instructions: CODE_REVIEW_TEMPLATE_MESSAGES.instructions,
    license: 'MIT',
    compatibility: CODE_REVIEW_TEMPLATE_MESSAGES.skillCompatibility,
    metadata: { author: 'openspec', version: '1.0' },
  };
}

export function getOpsxCodeReviewCommandTemplate(): CommandTemplate {
  return {
    name: 'OPSX: Code Review',
    description: CODE_REVIEW_TEMPLATE_MESSAGES.opsxDescription,
    category: 'Workflow',
    tags: ['workflow', 'review', 'code-review', 'experimental'],
    content: CODE_REVIEW_TEMPLATE_MESSAGES.instructions,
  };
}
