/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate } from '../types.js';

export function getFeedbackSkillTemplate(): SkillTemplate {
  return {
    name: 'feedback',
    description: 'Colete e envie feedback do usuário sobre o BR-OpenSpec com enriquecimento de contexto e anonimização.',
    instructions: `Ajude o usuário a enviar feedback sobre o BR-OpenSpec.

**Objetivo**: Guie o usuário através da coleta, enriquecimento e envio de feedback enquanto garante privacidade através de anonimização.

**Processo**

1. **Reúna contexto da conversa**
   - Revise o histórico recente da conversa para contexto
   - Identifique qual tarefa estava sendo realizada
   - Note o que funcionou bem ou mal
   - Capture pontos de fricção específicos ou elogios

2. **Elabore feedback enriquecido**
   - Crie um título claro e descritivo (uma única frase, sem prefixo "Feedback:" necessário)
   - Escreva um corpo que inclua:
     - O que o usuário estava tentando fazer
     - O que aconteceu (bom ou ruim)
     - Contexto relevante da conversa
     - Quaisquer sugestões ou pedidos específicos

3. **Anonimize informações sensíveis**
   - Substitua caminhos de arquivo por \`<path>\` ou descrições genéricas
   - Substitua chaves de API, tokens, segredos por \`<redacted>\`
   - Substitua nomes de empresa/organização por \`<company>\`
   - Substitua nomes pessoais por \`<user>\`
   - Substitua URLs específicas por \`<url>\` a menos que sejam públicas/relevantes
   - Mantenha detalhes técnicos que ajudam a entender o problema

4. **Apresente o rascunho para aprovação**
   - Mostre o rascunho completo ao usuário
   - Exiba tanto título quanto corpo claramente
   - Peça aprovação explícita antes de enviar
   - Permita que o usuário solicite modificações

5. **Envie após confirmação**
   - Use o comando \`openspec feedback\` para enviar
   - Formato: \`openspec feedback "título" --body "conteúdo do corpo"\`
   - O comando adicionará automaticamente metadados (versão, plataforma, timestamp)

**Exemplo de Rascunho**

\`\`\`
Título: O tratamento de erros no workflow de artifacts precisa melhorar

Corpo:
Eu estava trabalhando na criação de uma nova change e encontrei um problema com
o workflow de artifacts. Quando tentei continuar após criar a
proposal, o sistema não indicou claramente que eu precisava completar
os specs primeiro.

Sugestão: Adicione mensagens de erro mais claras que expliquem as cadeias de dependência
no workflow de artifacts. Algo como "Não é possível criar design.md
porque os specs não estão completos (0/2 done)."

Contexto: Usando o schema spec-driven com <path>/my-project
\`\`\`

**Exemplos de Anonimização**

Antes:
\`\`\`
Trabalhando em /Users/john/mycompany/auth-service/src/oauth.ts
Falhou com API key: sk_live_abc123xyz
Trabalhando na Acme Corp
\`\`\`

Depois:
\`\`\`
Trabalhando em <path>/oauth.ts
Falhou com API key: <redacted>
Trabalhando na <company>
\`\`\`

**Guardrails**

- DEVE mostrar o rascunho completo antes de enviar
- DEVE pedir aprovação explícita
- DEVE anonimizar informações sensíveis
- PERMITE que o usuário modifique o rascunho antes de enviar
- NÃO envie sem confirmação do usuário
- INCLUA contexto técnico relevante
- MANTENHA insights específicos da conversa

**Confirmação do Usuário Necessária**

Sempre pergunte:
\`\`\`
Aqui está o feedback que elaborei:

Título: [título]

Corpo:
[corpo]

Parece bom? Posso modificá-lo se quiser, ou enviá-lo como está.
\`\`\`

Só prossiga com o envio após o usuário confirmar.`,
    license: 'MIT',
    compatibility: 'Requer openspec CLI.',
    metadata: { author: 'openspec', version: '1.0' },
  };
}
