/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';

export function getOpsxProposeSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-propose',
    description: 'Proponha uma nova change com todos os artifacts gerados em um passo. Use quando o usuário quiser descrever rapidamente o que quer construir e obter uma proposal completa com design, specs e tasks prontos para implementação.',
    instructions: `Proponha uma nova change - crie a change e gere todos os artifacts em um passo.

**Fronteira de planejamento**: Este workflow cria apenas artifacts de planejamento. A solicitação do usuário que selecionou ou acionou este workflow autoriza apenas o planejamento, mesmo que peça para construir ou corrigir algo. Não edite código do projeto. Depois que os artifacts de planejamento estiverem completos, pare. Não inicie a implementação na mesma resposta, mesmo que a solicitação inicial peça isso. Aguarde uma nova solicitação do usuário após apresentar os artifacts; só então inicie o workflow de apply.

Vou criar uma change com os artifacts que o seu schema define. Com o schema spec-driven padrão, são:
- proposal.md (o que & por que)
- \`specs/<capability-path>/spec.md\` (o que o sistema deve fazer - um delta, não o spec principal)
- design.md (como)
- tasks.md (passos de implementação)

\`<capability-path>\` é o diretório do spec relativo a \`specs/\` (por exemplo, \`user-auth\` ou \`identity/user-auth\`). Preserve o caminho completo de uma capability existente e siga a organização já estabelecida no projeto para capabilities novas.

Quando o usuário estiver pronto para implementar, ele deve iniciar o workflow de apply explicitamente.

---

**Entrada**: A solicitação do usuário deve incluir um nome de change (kebab-case) OU uma descrição do que ele quer construir.

**Passos**

1. **Entenda a solicitação e esclareça ambiguidades relevantes**

   Se nenhuma entrada clara for fornecida, pergunte ao usuário (de forma aberta, sem opções pré-definidas):
   > "Em qual change você quer trabalhar? Descreva o que quer construir ou corrigir."

   A partir da descrição dele, derive um nome kebab-case (por exemplo, "adicionar autenticação de usuário" → \`add-user-auth\`).

   **IMPORTANTE**: NÃO prossiga sem entender o que o usuário quer construir.

   Se a solicitação contiver ambiguidade que afete de forma relevante o escopo, o comportamento externamente observável, a compatibilidade ou os critérios de aceitação, pergunte ao usuário antes de criar a change. Para detalhes menores, faça uma suposição razoável e registre-a nos artifacts de planejamento.

2. **Determine o schema de workflow**

   Use o schema padrão configurado a menos que o usuário solicite explicitamente um workflow diferente.

   **Use um schema diferente apenas se o usuário:**
   - Solicitar explicitamente um schema específico pelo nome → use \`--schema <nome-do-schema>\`
   - Pedir para "mostrar workflows" ou perguntar "quais workflows" existem → execute \`openspec schemas --json\` a partir do diretório de trabalho atual e deixe-o escolher

   Caso contrário, omita \`--schema\` para preservar o padrão configurado.

3. **Crie o diretório da change**

   Escolha uma das formas de schema abaixo.

   Usando o padrão configurado:
   \`\`\`bash
   openspec new change "<nome>"
   \`\`\`

   Usando um schema solicitado explicitamente:
   \`\`\`bash
   openspec new change "<nome>" --schema "<nome-do-schema>"
   \`\`\`
   Isso cria uma change com scaffold em \`openspec/changes/<nome>/\` com \`.openspec.yaml\`.

4. **Obtenha a ordem de construção dos artifacts**
   \`\`\`bash
   openspec status --change "<nome>" --json
   \`\`\`
   Analise o JSON para obter:
   - \`applyRequires\`: array de IDs de artifacts necessários antes da implementação (por exemplo, \`["tasks"]\`)
   - \`artifacts\`: lista de todos os artifacts, cada um com seu \`status\` e suas arestas \`requires\` (os IDs de artifact dos quais ele depende diretamente)

5. **Crie todos os artifacts do conjunto necessário**

   Use uma lista de tarefas para rastrear o progresso pelos artifacts.

   Percorra os artifacts em ordem de dependência (artifacts sem dependências pendentes primeiro):

   a. **Para cada artifact que está \`ready\` (dependências satisfeitas)**:
      - Obtenha instruções:
        \`\`\`bash
        openspec instructions <artifact-id> --change "<nome>" --json
        \`\`\`
      - O JSON de instruções inclui:
        - \`context\`: Contexto do projeto (restrições para você - NÃO inclua na saída)
        - \`rules\`: Regras específicas do artifact (restrições para você - NÃO inclua na saída)
        - \`template\`: A estrutura a ser usada para seu arquivo de saída
        - \`instruction\`: Orientação específica do schema para este tipo de artifact
        - \`skipped\`/\`warning\`: presentes quando a change declara skip_specs e este artifact NÃO deve ser criado - pare e escolha outro artifact
        - \`outputPath\`: Onde escrever o artifact
        - \`dependencies\`: Artifacts concluídos para ler como contexto
      - Leia quaisquer arquivos de dependências concluídos para contexto - sempre releia-os do disco, mesmo que já os tenha visto antes na conversa (o usuário pode tê-los editado)
      - Se o campo \`instruction\` delegar a criação a uma skill ou comando específico, invoque-o para produzir o artifact em vez de escrever o arquivo você mesmo, depois verifique se o arquivo do artifact existe em \`outputPath\`
      - Caso contrário, crie o arquivo do artifact usando \`template\` como a estrutura e escreva-o em \`outputPath\`; se for um glob, siga o \`instruction\` para escolher o caminho concreto do arquivo
      - Aplique \`context\` e \`rules\` como restrições - mas NÃO copie-os para o arquivo
      - Mostre breve progresso: "Criado <artifact-id>"

   b. **Continue até que todos os artifacts do conjunto necessário existam (não apenas o \`apply.requires\`)**
      - Após criar cada artifact, reexecute \`openspec status --change "<nome>" --json\`
      - O conjunto necessário é o \`applyRequires\` mais todo artifact alcançável a partir deles seguindo as arestas \`requires\` do \`status --json\` - percorra-as transitivamente (o spec-driven fecha sobre proposal, specs, design, tasks). Deixe artifacts fora desse conjunto em paz
      - Um artifact com \`status: "skipped"\` já está satisfeito: a change declara \`skip_specs\` em \`.openspec.yaml\`, então seus arquivos NÃO devem existir. Nunca tente criá-lo
      - O \`status\` é apenas existência de arquivo, então um artifact de \`applyRequires\` marcado como \`done\` NÃO significa que suas dependências existam - escrever \`tasks.md\` cedo marca \`tasks\` como done sem que \`specs\` jamais tenha sido escrito. Use as arestas \`requires\` de cada artifact, não o \`status\`, para montar o conjunto necessário: um artifact \`done\` ainda lista do que depende
      - Crie todo artifact do conjunto necessário que estiver faltando, depois verifique novamente - criar um pode desbloquear outros
      - Pule um apenas quando o próprio \`instruction\` dele disser que é condicional: execute \`openspec instructions <artifact-id> --change "<nome>" --json\` e pule somente se o campo \`instruction\` o marcar como opcional (por exemplo, "crie apenas se..."). O \`design.md\` do spec-driven se qualifica; \`specs\` nunca. Avise o usuário e não reconsidere
      - Dependências são facilitadoras, não portões: se um artifact necessário ainda estiver \`blocked\` apenas porque você pulou uma dependência condicional, escreva-o assim mesmo
      - Pare quando todos os artifacts do conjunto necessário estiverem \`done\` ou \`skipped\`, ou tiverem sido deliberadamente pulados

   c. **Se um artifact requerer entrada do usuário** (contexto incerto):
      - Peça esclarecimento ao usuário
      - Depois continue com a criação

6. **Mostre o status final**
   \`\`\`bash
   openspec status --change "<nome>"
   \`\`\`

**Saída**

Após completar todos os artifacts, resuma:
- Nome da change e localização
- Lista de artifacts criados com breves descrições, mais qualquer artifact condicional que você pulou e por quê
- O que está pronto: "Todos os artifacts necessários para a implementação estão prontos."
- Prompt: "Os artifacts estão prontos para revisão. Quando estiver pronto, execute \`/opsx:apply\` ou peça-me para aplicar esta change."

**Diretrizes de Criação de Artifacts**

- Siga o campo \`instruction\` de \`openspec instructions\` para cada tipo de artifact - ele é a orientação autoritativa, mesmo para nomes de artifact familiares
- Se o campo \`instruction\` direcionar você a usar uma skill ou comando específico para criar o artifact, invoque-o em vez de escrever o artifact diretamente
- O schema define o que cada artifact deve conter - siga-o
- Leia artifacts de dependência para contexto antes de criar novos
- Use \`template\` como a estrutura para seu arquivo de saída - preencha suas seções
- **IMPORTANTE**: \`context\` e \`rules\` são restrições para VOCÊ, não conteúdo para o arquivo
  - NÃO copie blocos \`<context>\`, \`<rules>\`, \`<project_context>\` para o artifact
  - Eles guiam o que você escreve, mas nunca devem aparecer na saída

**Guardrails**
- A solicitação que invocou este workflow autoriza apenas o planejamento. Qualquer instrução de implementação ou de apply contida nessa solicitação não é levada adiante. NÃO implemente a change, não inicie o workflow de apply nem edite código do projeto durante este workflow. Depois de apresentar os artifacts, pare e aguarde uma nova solicitação do usuário para iniciar o workflow de apply
- Crie todo artifact do qual a fase de apply depende transitivamente, não apenas os ids listados em \`apply.requires\`
- Sempre leia artifacts de dependência antes de criar um novo - releia do disco, não da memória da conversa (os arquivos podem ter mudado desde a última vez que você os viu)
- Pergunte sobre ambiguidades que mudariam de forma relevante o escopo, o comportamento externamente observável, a compatibilidade ou os critérios de aceitação; para detalhes menores, faça suposições razoáveis e registre-as
- Se uma change com aquele nome já existir, pergunte se o usuário quer continuar ela ou criar uma nova
- Verifique se cada arquivo do artifact existe após escrever antes de prosseguir para o próximo`,
    license: 'MIT',
    compatibility: 'Requer openspec CLI.',
    metadata: { author: 'openspec', version: '1.0' },
  };
}

export function getOpsxProposeCommandTemplate(): CommandTemplate {
  return {
    name: 'OPSX: Propose',
    description: 'Proponha uma nova change - crie-a e gere todos os artifacts em um passo',
    category: 'Workflow',
    tags: ['workflow', 'artifacts', 'experimental'],
    content: `Proponha uma nova change - crie a change e gere todos os artifacts em um passo.

**Fronteira de planejamento**: Este workflow cria apenas artifacts de planejamento. A solicitação do usuário que selecionou ou acionou este workflow autoriza apenas o planejamento, mesmo que peça para construir ou corrigir algo. Não edite código do projeto. Depois que os artifacts de planejamento estiverem completos, pare. Não inicie a implementação na mesma resposta, mesmo que a solicitação inicial peça isso. Aguarde uma nova solicitação do usuário após apresentar os artifacts; só então inicie o workflow de apply.

Vou criar uma change com os artifacts que o seu schema define. Com o schema spec-driven padrão, são:
- proposal.md (o que & por que)
- \`specs/<capability-path>/spec.md\` (o que o sistema deve fazer - um delta, não o spec principal)
- design.md (como)
- tasks.md (passos de implementação)

\`<capability-path>\` é o diretório do spec relativo a \`specs/\` (por exemplo, \`user-auth\` ou \`identity/user-auth\`). Preserve o caminho completo de uma capability existente e siga a organização já estabelecida no projeto para capabilities novas.

Quando o usuário estiver pronto para implementar, ele deve iniciar o workflow de apply explicitamente.

---

**Entrada**: O argumento após \`/opsx:propose\` é o nome da change (kebab-case), OU uma descrição do que o usuário quer construir.

**Passos**

1. **Entenda a solicitação e esclareça ambiguidades relevantes**

   Se nenhuma entrada for fornecida, pergunte ao usuário (de forma aberta, sem opções pré-definidas):
   > "Em qual change você quer trabalhar? Descreva o que quer construir ou corrigir."

   A partir da descrição dele, derive um nome kebab-case (por exemplo, "adicionar autenticação de usuário" → \`add-user-auth\`).

   **IMPORTANTE**: NÃO prossiga sem entender o que o usuário quer construir.

   Se a solicitação contiver ambiguidade que afete de forma relevante o escopo, o comportamento externamente observável, a compatibilidade ou os critérios de aceitação, pergunte ao usuário antes de criar a change. Para detalhes menores, faça uma suposição razoável e registre-a nos artifacts de planejamento.

2. **Determine o schema de workflow**

   Use o schema padrão configurado a menos que o usuário solicite explicitamente um workflow diferente.

   **Use um schema diferente apenas se o usuário:**
   - Solicitar explicitamente um schema específico pelo nome → use \`--schema <nome-do-schema>\`
   - Pedir para "mostrar workflows" ou perguntar "quais workflows" existem → execute \`openspec schemas --json\` a partir do diretório de trabalho atual e deixe-o escolher

   Caso contrário, omita \`--schema\` para preservar o padrão configurado.

3. **Crie o diretório da change**

   Escolha uma das formas de schema abaixo.

   Usando o padrão configurado:
   \`\`\`bash
   openspec new change "<nome>"
   \`\`\`

   Usando um schema solicitado explicitamente:
   \`\`\`bash
   openspec new change "<nome>" --schema "<nome-do-schema>"
   \`\`\`
   Isso cria uma change com scaffold em \`openspec/changes/<nome>/\` com \`.openspec.yaml\`.

4. **Obtenha a ordem de construção dos artifacts**
   \`\`\`bash
   openspec status --change "<nome>" --json
   \`\`\`
   Analise o JSON para obter:
   - \`applyRequires\`: array de IDs de artifacts necessários antes da implementação (por exemplo, \`["tasks"]\`)
   - \`artifacts\`: lista de todos os artifacts, cada um com seu \`status\` e suas arestas \`requires\` (os IDs de artifact dos quais ele depende diretamente)

5. **Crie todos os artifacts do conjunto necessário**

   Use uma lista de tarefas para rastrear o progresso pelos artifacts.

   Percorra os artifacts em ordem de dependência (artifacts sem dependências pendentes primeiro):

   a. **Para cada artifact que está \`ready\` (dependências satisfeitas)**:
      - Obtenha instruções:
        \`\`\`bash
        openspec instructions <artifact-id> --change "<nome>" --json
        \`\`\`
      - O JSON de instruções inclui:
        - \`context\`: Contexto do projeto (restrições para você - NÃO inclua na saída)
        - \`rules\`: Regras específicas do artifact (restrições para você - NÃO inclua na saída)
        - \`template\`: A estrutura a ser usada para seu arquivo de saída
        - \`instruction\`: Orientação específica do schema para este tipo de artifact
        - \`skipped\`/\`warning\`: presentes quando a change declara skip_specs e este artifact NÃO deve ser criado - pare e escolha outro artifact
        - \`outputPath\`: Onde escrever o artifact
        - \`dependencies\`: Artifacts concluídos para ler como contexto
      - Leia quaisquer arquivos de dependências concluídos para contexto - sempre releia-os do disco, mesmo que já os tenha visto antes na conversa (o usuário pode tê-los editado)
      - Se o campo \`instruction\` delegar a criação a uma skill ou comando específico, invoque-o para produzir o artifact em vez de escrever o arquivo você mesmo, depois verifique se o arquivo do artifact existe em \`outputPath\`
      - Caso contrário, crie o arquivo do artifact usando \`template\` como a estrutura e escreva-o em \`outputPath\`; se for um glob, siga o \`instruction\` para escolher o caminho concreto do arquivo
      - Aplique \`context\` e \`rules\` como restrições - mas NÃO copie-os para o arquivo
      - Mostre breve progresso: "Criado <artifact-id>"

   b. **Continue até que todos os artifacts do conjunto necessário existam (não apenas o \`apply.requires\`)**
      - Após criar cada artifact, reexecute \`openspec status --change "<nome>" --json\`
      - O conjunto necessário é o \`applyRequires\` mais todo artifact alcançável a partir deles seguindo as arestas \`requires\` do \`status --json\` - percorra-as transitivamente (o spec-driven fecha sobre proposal, specs, design, tasks). Deixe artifacts fora desse conjunto em paz
      - Um artifact com \`status: "skipped"\` já está satisfeito: a change declara \`skip_specs\` em \`.openspec.yaml\`, então seus arquivos NÃO devem existir. Nunca tente criá-lo
      - O \`status\` é apenas existência de arquivo, então um artifact de \`applyRequires\` marcado como \`done\` NÃO significa que suas dependências existam - escrever \`tasks.md\` cedo marca \`tasks\` como done sem que \`specs\` jamais tenha sido escrito. Use as arestas \`requires\` de cada artifact, não o \`status\`, para montar o conjunto necessário: um artifact \`done\` ainda lista do que depende
      - Crie todo artifact do conjunto necessário que estiver faltando, depois verifique novamente - criar um pode desbloquear outros
      - Pule um apenas quando o próprio \`instruction\` dele disser que é condicional: execute \`openspec instructions <artifact-id> --change "<nome>" --json\` e pule somente se o campo \`instruction\` o marcar como opcional (por exemplo, "crie apenas se..."). O \`design.md\` do spec-driven se qualifica; \`specs\` nunca. Avise o usuário e não reconsidere
      - Dependências são facilitadoras, não portões: se um artifact necessário ainda estiver \`blocked\` apenas porque você pulou uma dependência condicional, escreva-o assim mesmo
      - Pare quando todos os artifacts do conjunto necessário estiverem \`done\` ou \`skipped\`, ou tiverem sido deliberadamente pulados

   c. **Se um artifact requerer entrada do usuário** (contexto incerto):
      - Peça esclarecimento ao usuário
      - Depois continue com a criação

6. **Mostre o status final**
   \`\`\`bash
   openspec status --change "<nome>"
   \`\`\`

**Saída**

Após completar todos os artifacts, resuma:
- Nome da change e localização
- Lista de artifacts criados com breves descrições, mais qualquer artifact condicional que você pulou e por quê
- O que está pronto: "Todos os artifacts necessários para a implementação estão prontos."
- Prompt: "Os artifacts estão prontos para revisão. Quando estiver pronto, execute \`/opsx:apply\`."

**Diretrizes de Criação de Artifacts**

- Siga o campo \`instruction\` de \`openspec instructions\` para cada tipo de artifact - ele é a orientação autoritativa, mesmo para nomes de artifact familiares
- Se o campo \`instruction\` direcionar você a usar uma skill ou comando específico para criar o artifact, invoque-o em vez de escrever o artifact diretamente
- O schema define o que cada artifact deve conter - siga-o
- Leia artifacts de dependência para contexto antes de criar novos
- Use \`template\` como a estrutura para seu arquivo de saída - preencha suas seções
- **IMPORTANTE**: \`context\` e \`rules\` são restrições para VOCÊ, não conteúdo para o arquivo
  - NÃO copie blocos \`<context>\`, \`<rules>\`, \`<project_context>\` para o artifact
  - Eles guiam o que você escreve, mas nunca devem aparecer na saída

**Guardrails**
- A solicitação que invocou este workflow autoriza apenas o planejamento. Qualquer instrução de implementação ou de apply contida nessa solicitação não é levada adiante. NÃO implemente a change, não inicie o workflow de apply nem edite código do projeto durante este workflow. Depois de apresentar os artifacts, pare e aguarde uma nova solicitação do usuário para iniciar o workflow de apply
- Crie todo artifact do qual a fase de apply depende transitivamente, não apenas os ids listados em \`apply.requires\`
- Sempre leia artifacts de dependência antes de criar um novo - releia do disco, não da memória da conversa (os arquivos podem ter mudado desde a última vez que você os viu)
- Pergunte sobre ambiguidades que mudariam de forma relevante o escopo, o comportamento externamente observável, a compatibilidade ou os critérios de aceitação; para detalhes menores, faça suposições razoáveis e registre-as
- Se uma change com aquele nome já existir, pergunte se o usuário quer continuar ela ou criar uma nova
- Verifique se cada arquivo do artifact existe após escrever antes de prosseguir para o próximo`
  };
}
