/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';

export function getOpsxProposeSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-propose',
    description: 'Proponha uma nova change com todos os artifacts gerados em um passo. Use quando o usuário quiser descrever rapidamente o que quer construir e obter uma proposal completa com design, specs e tasks prontos para implementação.',
    instructions: `Proponha uma nova change - crie a change e gere todos os artifacts em um passo.

Vou criar uma change com artifacts:
- proposal.md (o que & por que)
- design.md (como)
- tasks.md (passos de implementação)

Quando pronto para implementar, execute /opsx:apply

---

**Entrada**: A solicitação do usuário deve incluir um nome de change (kebab-case) OU uma descrição do que ele quer construir.

**Passos**

1. **Se nenhuma entrada clara for fornecida, pergunte o que ele quer construir**

   Use a ferramenta **AskUserQuestion** (aberta, sem opções pré-definidas) para perguntar:
   > "Em qual change você quer trabalhar? Descreva o que quer construir ou corrigir."

   A partir da descrição dele, derive um nome kebab-case (por exemplo, "adicionar autenticação de usuário" → \`add-user-auth\`).

   **IMPORTANTE**: NÃO prossiga sem entender o que o usuário quer construir.

2. **Crie o diretório da change**
   \`\`\`bash
   openspec new change "<nome>"
   \`\`\`
   Isso cria uma change com scaffold em \`openspec/changes/<nome>/\` com \`.openspec.yaml\`.

3. **Obtenha a ordem de construção dos artifacts**
   \`\`\`bash
   openspec status --change "<nome>" --json
   \`\`\`
   Analise o JSON para obter:
   - \`applyRequires\`: array de IDs de artifacts necessários antes da implementação (por exemplo, \`["tasks"]\`)
   - \`artifacts\`: lista de todos os artifacts com seu status e dependências

4. **Crie artifacts em sequência até estar pronto para apply**

   Use a ferramenta **TodoWrite** para rastrear o progresso pelos artifacts.

   Percorra os artifacts em ordem de dependência (artifacts sem dependências pendentes primeiro):

   a. **Para cada artifact que está \`ready\` (dependências satisfeitas)**:
      - Obtenha instruções:
        \`\`\`bash
        openspec instructions <artifact-id> --change "<nome>" --json
        \`\`\`
      - O JSON de instruções inclui:
        - \`context\`: Contexto do projeto (restrições para você - NÃO inclua na saída)
        - \`rules\`: Regras específicas do artifact (restrições para você - NÃO inclua na saída)
        - \`template\`: A estrutura a ser usada para seu arquivo de saída
        - \`instruction\`: Orientação específica do schema para este tipo de artifact
        - \`outputPath\`: Onde escrever o artifact
        - \`dependencies\`: Artifacts concluídos para ler como contexto
      - Leia quaisquer arquivos de dependências concluídos para contexto
      - Crie o arquivo do artifact usando \`template\` como a estrutura
      - Aplique \`context\` e \`rules\` como restrições - mas NÃO copie-os para o arquivo
      - Mostre breve progresso: "Criado <artifact-id>"

   b. **Continue até todos os artifacts \`applyRequires\` estarem completos**
      - Após criar cada artifact, reexecute \`openspec status --change "<nome>" --json\`
      - Verifique se cada ID de artifact em \`applyRequires\` tem \`status: "done"\` no array de artifacts
      - Pare quando todos os artifacts \`applyRequires\` estiverem done

   c. **Se um artifact requerer entrada do usuário** (contexto incerto):
      - Use a ferramenta **AskUserQuestion** para esclarecer
      - Depois continue com a criação

5. **Mostre o status final**
   \`\`\`bash
   openspec status --change "<nome>"
   \`\`\`

**Saída**

Após completar todos os artifacts, resuma:
- Nome da change e localização
- Lista de artifacts criados com breves descrições
- O que está pronto: "Todos os artifacts criados! Pronto para implementação."
- Prompt: "Execute \`/opsx:apply\` ou peça-me para implementar para começar a trabalhar nas tarefas."

**Diretrizes de Criação de Artifacts**

- Siga o campo \`instruction\` de \`openspec instructions\` para cada tipo de artifact
- O schema define o que cada artifact deve conter - siga-o
- Leia artifacts de dependência para contexto antes de criar novos
- Use \`template\` como a estrutura para seu arquivo de saída - preencha suas seções
- **IMPORTANTE**: \`context\` e \`rules\` são restrições para VOCÊ, não conteúdo para o arquivo
  - NÃO copie blocos \`<context>\`, \`<rules>\`, \`<project_context>\` para o artifact
  - Eles guiam o que você escreve, mas nunca devem aparecer na saída

**Guardrails**
- Crie TODOS os artifacts necessários para implementação (conforme definido pelo \`apply.requires\` do schema)
- Sempre leia artifacts de dependência antes de criar um novo
- Se o contexto estiver criticamente incerto, pergunte ao usuário - mas prefira tomar decisões razoáveis para manter o momento
- Se uma change com aquele nome já existir, pergunte se o usuário quer continuar ela ou criar uma nova
- Verifique se cada arquivo do artifact existe após escrever antes de prosseguir para o próximo`,
    license: 'MIT',
    compatibility: 'Requer openspec CLI.',
    metadata: { author: 'openspec', version: '1.0' },
  };
}

export function getOpsxProposeCommandTemplate(): CommandTemplate {
  return {
    name: 'OPSX: Propose',
    description: 'Proponha uma nova change - crie-a e gere todos os artifacts em um passo',
    category: 'Workflow',
    tags: ['workflow', 'artifacts', 'experimental'],
    content: `Proponha uma nova change - crie a change e gere todos os artifacts em um passo.

Vou criar uma change com artifacts:
- proposal.md (o que & por que)
- design.md (como)
- tasks.md (passos de implementação)

Quando pronto para implementar, execute /opsx:apply

---

**Entrada**: O argumento após \`/opsx:propose\` é o nome da change (kebab-case), OU uma descrição do que o usuário quer construir.

**Passos**

1. **Se nenhuma entrada for fornecida, pergunte o que ele quer construir**

   Use a ferramenta **AskUserQuestion** (aberta, sem opções pré-definidas) para perguntar:
   > "Em qual change você quer trabalhar? Descreva o que quer construir ou corrigir."

   A partir da descrição dele, derive um nome kebab-case (por exemplo, "adicionar autenticação de usuário" → \`add-user-auth\`).

   **IMPORTANTE**: NÃO prossiga sem entender o que o usuário quer construir.

2. **Crie o diretório da change**
   \`\`\`bash
   openspec new change "<nome>"
   \`\`\`
   Isso cria uma change com scaffold em \`openspec/changes/<nome>/\` com \`.openspec.yaml\`.

3. **Obtenha a ordem de construção dos artifacts**
   \`\`\`bash
   openspec status --change "<nome>" --json
   \`\`\`
   Analise o JSON para obter:
   - \`applyRequires\`: array de IDs de artifacts necessários antes da implementação (por exemplo, \`["tasks"]\`)
   - \`artifacts\`: lista de todos os artifacts com seu status e dependências

4. **Crie artifacts em sequência até estar pronto para apply**

   Use a ferramenta **TodoWrite** para rastrear o progresso pelos artifacts.

   Percorra os artifacts em ordem de dependência (artifacts sem dependências pendentes primeiro):

   a. **Para cada artifact que está \`ready\` (dependências satisfeitas)**:
      - Obtenha instruções:
        \`\`\`bash
        openspec instructions <artifact-id> --change "<nome>" --json
        \`\`\`
      - O JSON de instruções inclui:
        - \`context\`: Contexto do projeto (restrições para você - NÃO inclua na saída)
        - \`rules\`: Regras específicas do artifact (restrições para você - NÃO inclua na saída)
        - \`template\`: A estrutura a ser usada para seu arquivo de saída
        - \`instruction\`: Orientação específica do schema para este tipo de artifact
        - \`outputPath\`: Onde escrever o artifact
        - \`dependencies\`: Artifacts concluídos para ler como contexto
      - Leia quaisquer arquivos de dependências concluídos para contexto
      - Crie o arquivo do artifact usando \`template\` como a estrutura
      - Aplique \`context\` e \`rules\` como restrições - mas NÃO copie-os para o arquivo
      - Mostre breve progresso: "Criado <artifact-id>"

   b. **Continue até todos os artifacts \`applyRequires\` estarem completos**
      - Após criar cada artifact, reexecute \`openspec status --change "<nome>" --json\`
      - Verifique se cada ID de artifact em \`applyRequires\` tem \`status: "done"\` no array de artifacts
      - Pare quando todos os artifacts \`applyRequires\` estiverem done

   c. **Se um artifact requerer entrada do usuário** (contexto incerto):
      - Use a ferramenta **AskUserQuestion** para esclarecer
      - Depois continue com a criação

5. **Mostre o status final**
   \`\`\`bash
   openspec status --change "<nome>"
   \`\`\`

**Saída**

Após completar todos os artifacts, resuma:
- Nome da change e localização
- Lista de artifacts criados com breves descrições
- O que está pronto: "Todos os artifacts criados! Pronto para implementação."
- Prompt: "Execute \`/opsx:apply\` para começar a implementar."

**Diretrizes de Criação de Artifacts**

- Siga o campo \`instruction\` de \`openspec instructions\` para cada tipo de artifact
- O schema define o que cada artifact deve conter - siga-o
- Leia artifacts de dependência para contexto antes de criar novos
- Use \`template\` como a estrutura para seu arquivo de saída - preencha suas seções
- **IMPORTANTE**: \`context\` e \`rules\` são restrições para VOCÊ, não conteúdo para o arquivo
  - NÃO copie blocos \`<context>\`, \`<rules>\`, \`<project_context>\` para o artifact
  - Eles guiam o que você escreve, mas nunca devem aparecer na saída

**Guardrails**
- Crie TODOS os artifacts necessários para implementação (conforme definido pelo \`apply.requires\` do schema)
- Sempre leia artifacts de dependência antes de criar um novo
- Se o contexto estiver criticamente incerto, pergunte ao usuário - mas prefira tomar decisões razoáveis para manter o momento
- Se uma change com aquele nome já existir, pergunte se o usuário quer continuar ela ou criar uma nova
- Verifique se cada arquivo do artifact existe após escrever antes de prosseguir para o próximo`
  };
}
